CREATE TABLE EMPLOYEE(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name NVARCHAR(MAX) COLLATE Khmer_100_BIN,
	Salary MONEY,
	Phone VARCHAR(13),
	HireDate DATE,
	StopDate DATE,
	Photo VARBINARY(MAX)
)

GO