CREATE TABLE PRODUCT(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name NVARCHAR(MAX) COLLATE Khmer_100_BIN,
	Price MONEY,
	MadeDate DATE,
	ExpiredDate DATE,
	Photo VARBINARY(MAX),
	Active BIT
)
GO

CREATE TABLE CUSTOMER (
ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
Name NVARCHAR(MAX) COLLATE Khmer_100_BIN,
Phone VARCHAR(13),
Photo VARBINARY(MAX)
)
GO
CREATE TABLE SUPPLIER(
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name NVARCHAR(MAX) COLLATE Khmer_100_BIN,
	Phone VARCHAR(13),
	Descript NVARCHAR(MAX) COLLATE khmer_100_BIN, 
	Photo VARBINARY(MAX)
	)
GO
CREATE TABLE [USER](
		
	ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	UserName VARCHAR(MAX),
	UserPassword  VARCHAR(MAX),
	Position VARCHAR(MAX)
	
)
GO
