Create Database INVENTORY On (Name = INVENTORY, FileName = "D:\Database\INVENTORY.mdf",
Size = 5MB,MaxSize = Unlimited, FileGrowth = 2MB)
Log On (Name = INVENTORY_log, FileName = "D:\Database\INVENTORY_log.ldf",
Size = 4MB, MaxSize = Unlimited, FileGrowth =10%)

GO
CREATE TABLE [USER]
(
	ID UNIQUEIDENTIFIER CONSTRAINT USER_PK PRIMARY KEY DEFAULT NEWID(),			
	FirstName NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 ,
	LastName NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 ,
	Username NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 CONSTRAINT IX_USER_UserName_UK UNIQUE NULL,
	[Password] NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	Position NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	Phone NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,	
	Active BIT NOT NULL DEFAULT 1,

	CreatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	CreatedDate DATETIME NULL,
	UpdatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	UpdatedDate DATETIME NULL
)
GO
CREATE TABLE [GROUP]
(
	ID UNIQUEIDENTIFIER CONSTRAINT GROUP_PK PRIMARY KEY DEFAULT NEWID(),
	GroupName  NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 CONSTRAINT IX_GROUP_GroupName_UK UNIQUE NULL,
	[Description] NVARCHAR(2500) COLLATE SQL_Latin1_General_CP437_BIN2 ,
	
	CreatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	CreatedDate DATETIME NULL,
	UpdatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	UpdatedDate DATETIME NULL
)
GO
CREATE TABLE USER_GROUP
(
	ID UNIQUEIDENTIFIER CONSTRAINT USER_GROUP_PK PRIMARY KEY DEFAULT NEWID(),
	UserId UNIQUEIDENTIFIER,
	GroupId UNIQUEIDENTIFIER,
	CONSTRAINT USER_PK_USER_FK FOREIGN KEY(UserId)REFERENCES [USER](ID),
	CONSTRAINT USER_PK_GROUP_FK FOREIGN KEY(GroupId)REFERENCES [GROUP](ID),

	CreatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	CreatedDate DATETIME NULL,
	UpdatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	UpdatedDate DATETIME NULL
)
GO
CREATE TABLE [ROLE]
(
	ID UNIQUEIDENTIFIER CONSTRAINT ROLE_PK PRIMARY KEY DEFAULT NEWID(),
	Title  NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 CONSTRAINT IX_RoleName_UK UNIQUE NULL,
	GroupName  NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 CONSTRAINT IX_USER_GROUP_GroupName_UK UNIQUE NULL,
	[Description] NVARCHAR(2500) COLLATE SQL_Latin1_General_CP437_BIN2 ,
	
	CreatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	CreatedDate DATETIME NULL,
	UpdatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	UpdatedDate DATETIME NULL
)
GO
CREATE TABLE GROUP_ROLE
(
	ID UNIQUEIDENTIFIER CONSTRAINT GROUP_ROLE_PK PRIMARY KEY DEFAULT NEWID(),
	RoleId UNIQUEIDENTIFIER,
	GroupId UNIQUEIDENTIFIER,
	CONSTRAINT ROLE_PK_ROLE_FK FOREIGN KEY(RoleId)REFERENCES [ROLE](ID),
	CONSTRAINT GROUP_PK_GROUP_ROLE_FK FOREIGN KEY(GroupId)REFERENCES [GROUP](ID),

	CreatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	CreatedDate DATETIME NULL,
	UpdatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	UpdatedDate DATETIME NULL
)
GO
CREATE TABLE USER_ROLE
(
	ID UNIQUEIDENTIFIER CONSTRAINT USER_ROLE_PK PRIMARY KEY DEFAULT NEWID(),
	RoleId UNIQUEIDENTIFIER,
	UserId UNIQUEIDENTIFIER,
	CONSTRAINT ROLE_PK_USER_ROLE_FK FOREIGN KEY(RoleId)REFERENCES [ROLE](ID),
	CONSTRAINT USER_PK_USER_ROLE_FK FOREIGN KEY(UserId)REFERENCES [USER](ID),

	CreatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	CreatedDate DATETIME NULL,
	UpdatedBy NVARCHAR(255) COLLATE SQL_Latin1_General_CP437_BIN2 NULL,
	UpdatedDate DATETIME NULL
)